#!/bin/sh
#
# File: .aliases
# Description:
#   contains all aliases defined by the user. Separated from shell rc files
#   for portability between different machines.
#   Avoid syntax and commands not portable to other different setups,
#   check out http://hyperpolyglot.org/unix-shells for more information

# checks if argument exists in path
exists() { command -p -v &>/dev/null }
is_zsh() { [ -n "$ZSH_VERSION" ] }
is_darwin() { [ $(uname) = Darwin ] }

# ls
# order of output:
# symbols, UPPERCASE, lowercase (folders first)
unalias ls 2>/dev/null
unfunction ls 2>/dev/null
alias l='LC_COLLATE=C ls -h --color=always --dereference-command-line-symlink-to-dir --group-directories-first'
alias ll='l -lF'
alias la='l -A'
alias lla='ll -AF'

# safe copy, move and delete
alias cp='cp -i'
alias mv='mv -i'
alias rm='rm -I'
if is_darwin; then
    unalias rm 2>/dev/null
    ! exists grm || alias rm='command grm -I'
fi

# directories
unalias mkdir 2>/dev/null
alias md='mkdir -p'
alias rd='rmdir'
alias po='popd'
alias pu='pushd'

# hdd
is_darwin && alias df='df -h' || alias df='df -h -x squashfs'
alias du='du -h'

# summary of disk used by child items sorted and unsorted
alias dus='LANG=C du -s *'
alias duss='dus | LANG=C sort -h'
# disk space used by system folders
alias dusss="LANG=C du -s /{{boot,lib*,opt,sbin,tmp,usr,var}/*(N),{bin,etc,root}} 2>/dev/null | grep -vE '^(0|[0-9.]+K)' | LANG=C sort -h"

alias diff='command diff -u --color'

# sudo aliases
alias sudo='sudo '                      # expand aliases after sudo
alias usersu='sudo -E -s'               # preserve environment (-E option) when login as root
alias sudoit='sudo env PATH="$PATH" '   # preserve user PATH

## git

alias gap='git add -p'
alias gdw='git diff -w'
alias gds='git diff --staged'
alias gdsw='git diff --staged -w'

# git fetch
alias gf='git fetch --prune'
alias gfa='gf --all'

alias gpll='git pull'
alias gpsh='git push'

# git push
alias gpa='git push --all'
alias gpfa='git push --force-with-lease --all'
# prune remote branches
alias gpp='git push --prune --all'

# git pretty log
alias gl='git log --oneline --graph --decorate --color'
alias gla='git log --oneline --graph --decorate --color --all'
# Adds author and relative commit date
alias glg='git log --graph --pretty=format:"%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %Cblue<%an>%Creset" --abbrev-commit --date=relative'
alias glga='git log --graph --pretty=format:"%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %Cblue<%an>%Creset" --abbrev-commit --date=relative --all'

# git reset
alias grhs='git reset --soft'
alias 'grh!'="git reset --hard"
unalias grhh 2>/dev/null

## utilities

# open with system default application
alias o='open_command'
alias o.='o .'

# enable advanced calculation in bc by default
alias bc='bc -l'

# default parameters for youtube-dl
alias ytdl='youtube-dl --prefer-ffmpeg -o "%(title)s.%(ext)s"'

# terminating global aliases
is_zsh && {
    alias -g :L='| command less'
    alias -g :H='| command head'
    alias -g :T='| command tail'
    alias -g :G='| command grep'
    alias -g :LL='2>&1 | command less'
    alias -g :NE='2>/dev/null'
    alias -g :NO='1>/dev/null'
    alias -g :NUL='&>/dev/null'
}

# ip command
alias ip='ip -color'
alias ipb='ip -color -brief'

# Visual Studio Code
alias vsc='code-insiders'
alias vsc.='code-insiders .'
alias ohmyzsh='vsc "$ZSH"'
alias zshrc='vsc "${ZDOTDIR:-$HOME}/.zshrc"'

# last exit status
alias '?'='echo $?'
