#!/bin/sh
#
# File: .aliases
# Description:
#   contains all aliases defined by the user. Separated from shell rc files
#   for portability between different machines.
#   Avoid syntax and commands not portable to other different setups,
#   check out http://hyperpolyglot.org/unix-shells for more information

# checks if argument exists in path
alias exists='command -v &>/dev/null'

# ls
# order of output:
# symbols, UPPERCASE, lowercase (folders first)
alias lf='LC_COLLATE=C ls -h --color=always --dereference-command-line-symlink-to-dir --group-directories-first'
alias l='lf'
alias llf='lf -lF'
alias ll='llf'
alias lfa='lf -A'
alias la='lfa'
alias llfa='llf -AF'
alias lla='llfa'

# safe copy, move and delete
alias cp='cp -i'
alias mv='mv -i'
alias rm='rm -I'

# directories
alias mkdir &>/dev/null && unalias mkdir # remove nocorrect (oh-my-zsh)
alias md='mkdir -p'
alias rd='rmdir'
[[ -d /C ]] && alias sistema='cd /C'
[[ -d /D ]] && alias dades='cd /D'

# hdd
alias df='df -h'
alias du='du -h'

alias dus='du -s *'
alias duss='du -s * | sort -h'
alias dusss="LANG=C du -s /{{boot,lib*,opt,sbin,tmp,usr,var}/*,{bin,etc,root}} 2>/dev/null | grep -vE '^(0|[0-9.]+K)' | LANG=C sort -h"

# expand aliases after sudo
alias sudo='sudo '
# preserve environment (-E option) when login as root
alias sudoas='sudo -E -s'

## git

alias gau='git add -u'
alias gap='git add -p'

alias gst='git status -sb'

alias gcob='git checkout -b'

# git fetch
alias gf='git fetch --prune'
alias gfa='gf --all'

# git push
alias gp='git push'
alias gpa='git push --all'
alias gpf='git push --force'
alias gpfa='git push --force --all'
# prune remote branches
alias gpp='git push --prune --all'

# git pretty log
alias gl='git log --oneline --graph --decorate --color'
alias gla='git log --oneline --graph --decorate --color --all'
alias glg='git log --graph --pretty=format:"%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %Cblue<%an>%Creset" --abbrev-commit --date=relative'
alias glga='git log --graph --pretty=format:"%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %Cblue<%an>%Creset" --abbrev-commit --date=relative --all'

# git diff
alias gd='git diff'
alias gds='git diff --staged'
alias gdw='git diff --word-diff'
alias gdcw='git diff --cached --word-diff'

## utilities

# open with system default application
alias o='open_command'
alias o.='o .'

# stdin to clipboard
alias xclip='xclip -selection c'

# enable advanced calculation in bc by default
alias bc='bc -l'

# default parameters for youtube-dl
alias ytdl="youtube-dl -o '%(title)s.%(ext)s'"
